name: Update README with Recent Activity

on:
  schedule:
    - cron: "0 * * * *"  # every hour
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update_activity:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: Readme-Workflows/recent-activity@v2.4.1
        env:
          GH_USERNAME: Dantdmnl
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
