name: Update README with recent activity

on:
  schedule:
    - cron: "0 * * * *" # every hour
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Readme-Workflows/recent-activity@v2
        with:
          COMMIT_MSG: "chore: update activity section"
